### ISSUE TITLE
Criar o arquivo 5w2h.md

### ISSUE THREAD

**Issue by e026ti** [eteabs/analise-de-sistemas-2S-2018-pet-save#3]
O conteúdo que já está no [arquivo anexado do 5w2h](https://github.com/eteabs/analise-de-sistemas-2S-2018-pet-save/blob/master/5w2h.docx) poderia ser inserido neste arquivo.

**Comment by Felipe-Cavalca** [comment]
ja criei o arquivo 5w2h.md
