### ISSUE TITLE
Faltando fechamento do PHP

### ISSUE THREAD

**Issue by lucasgdb** [eteabs/analise-de-sistemas-2S-2018-pet-save#5]
Em alguns arquivos .php está faltando completar o ?> do fechamento do PHP

<img src="https://i.imgur.com/QXeFx2e.png"/>
<img src="https://i.imgur.com/8cBwkf3.png"/>
<img src="https://i.imgur.com/BGRHEXm.png"/>

**Comment by e026ti** [comment]
@LucasNaja , a tag de fechamento é [opcional](https://secure.php.net/basic-syntax.instruction-separation). Existe uma recomendação chamada [PSR-2](https://github.com/php-brasil/fig-standards-pt_BR/blob/master/accepted/PSR-2-coding-style-guide.md#22-arquivos) que sugere que quando um arquivo só tem código, a tag de fechamento `?>` seja omitida.

Interessante dizer, que desde a versão 5.4.0 do PHP, pode-se usar a short tag `<?= ?>`  para `<?php echo ?>` sem precisar habilitar no php.ini
Fonte:https://secure.php.net/manual/pt_BR/function.echo.php

Agora se a equipe vai seguir estas recomendações depende deles.

Aproveitando, porque não usar a tag de fechamento é recomendável? Alguém sabe?

PS: @LucasNaja , obrigado pela contribuição!

**Comment by lucasgdb** [comment]
Muito bom, não sabia dessa omissão da tag de fechamento do PHP, obrigado pelo esclarecimento @e026ti :)
Sobre a questão, o único contato que tive com PHP foi no curso de Laravel da SeTI, então deixo para meus colegas 😅
Obrigado novamente!
